version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/stage/django/Dockerfile
    image: mdbee_stage_django
    depends_on:
      - redis
    env_file:
      - ./.envs/.stage/.django
      - ./.envs/.stage/.postgres
    command: /start
    expose:
      - 8000

  channelworker:
    <<: *django
    image: mdbee_stage_channelworker
    command: /start-channelworker

  redis:
    image: redis:6.0.8

  celeryworker:
    <<: *django
    image: mdbee_stage_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: mdbee_stage_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: mdbee_stage_flower
    ports:
      - "5555:5555"
    command: /start-flower

  highchart:
    build:
      context: .
      dockerfile: ./compose/stage/highchart-export-server/Dockerfile
    image: highchart-export-server
    ports:
      - "8889:8080"
