#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python3 /app/manage.py migrate
/usr/local/bin/daphne -b 0.0.0.0 -p 8000 config.asgi:application
