# Generated by Django 2.2.7 on 2020-05-23 12:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=255, unique=True)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
