# Generated by Django 2.2.7 on 2020-05-23 12:38

from django.db import migrations

initial_settings = [
    {
        'setting_name': 'session_timeout',
        'value': 30
    },
    {
        'setting_name': 'otp_resend_timeout',
        'value': 30
    },
{
        'setting_name': 'show_announcements',
        'value': False
    }
]


def create_settings(apps, schema_editor):
    ApplicationSettings = apps.get_model('synergy_auth', 'ApplicationSettings')
    default_types_objs = [ApplicationSettings(**initial_setting) for initial_setting in initial_settings]
    ApplicationSettings.objects.bulk_create(default_types_objs)


def delete_settings(apps, schema_editor):
    ApplicationSettings = apps.get_model('synergy_auth', 'ApplicationSettings')
    ApplicationSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('synergy_auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_settings, delete_settings),
    ]
